// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: rdpc/rdpc.proto

package rdpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_rdpc_rdpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_rdpc_rdpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{1}
}

func (x *Items) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Realm          string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Category       string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory    string                 `protobuf:"bytes,4,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	Icon           string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	IconTierText   string                 `protobuf:"bytes,6,opt,name=icon_tier_text,json=iconTierText,proto3" json:"icon_tier_text,omitempty"`
	Name           string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	BaseType       string                 `protobuf:"bytes,8,opt,name=base_type,json=baseType,proto3" json:"base_type,omitempty"`
	Rarity         string                 `protobuf:"bytes,9,opt,name=rarity,proto3" json:"rarity,omitempty"`
	W              int32                  `protobuf:"varint,10,opt,name=w,proto3" json:"w,omitempty"`
	H              int32                  `protobuf:"varint,11,opt,name=h,proto3" json:"h,omitempty"`
	Ilvl           int32                  `protobuf:"varint,12,opt,name=ilvl,proto3" json:"ilvl,omitempty"`
	SocketedItems  []byte                 `protobuf:"bytes,13,opt,name=socketed_items,json=socketedItems,proto3" json:"socketed_items,omitempty"`
	Properties     []byte                 `protobuf:"bytes,14,opt,name=properties,proto3" json:"properties,omitempty"`
	Requirements   []byte                 `protobuf:"bytes,15,opt,name=requirements,proto3" json:"requirements,omitempty"`
	EnchantMods    []byte                 `protobuf:"bytes,16,opt,name=enchant_mods,json=enchantMods,proto3" json:"enchant_mods,omitempty"`
	RuneMods       []byte                 `protobuf:"bytes,17,opt,name=rune_mods,json=runeMods,proto3" json:"rune_mods,omitempty"`
	ImplicitMods   []byte                 `protobuf:"bytes,18,opt,name=implicit_mods,json=implicitMods,proto3" json:"implicit_mods,omitempty"`
	ExplicitMods   []byte                 `protobuf:"bytes,19,opt,name=explicit_mods,json=explicitMods,proto3" json:"explicit_mods,omitempty"`
	FracturedMods  []byte                 `protobuf:"bytes,20,opt,name=fractured_mods,json=fracturedMods,proto3" json:"fractured_mods,omitempty"`
	DesecratedMods []byte                 `protobuf:"bytes,21,opt,name=desecrated_mods,json=desecratedMods,proto3" json:"desecrated_mods,omitempty"`
	FlavourText    string                 `protobuf:"bytes,22,opt,name=flavour_text,json=flavourText,proto3" json:"flavour_text,omitempty"`
	DescrText      string                 `protobuf:"bytes,23,opt,name=descr_text,json=descrText,proto3" json:"descr_text,omitempty"`
	SecDescrText   string                 `protobuf:"bytes,24,opt,name=sec_descr_text,json=secDescrText,proto3" json:"sec_descr_text,omitempty"`
	Support        bool                   `protobuf:"varint,25,opt,name=support,proto3" json:"support,omitempty"`
	Duplicated     bool                   `protobuf:"varint,26,opt,name=duplicated,proto3" json:"duplicated,omitempty"`
	Corrupted      bool                   `protobuf:"varint,27,opt,name=corrupted,proto3" json:"corrupted,omitempty"`
	Sanctified     bool                   `protobuf:"varint,28,opt,name=sanctified,proto3" json:"sanctified,omitempty"`
	Desecrated     bool                   `protobuf:"varint,29,opt,name=desecrated,proto3" json:"desecrated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_rdpc_rdpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *Item) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Item) GetIconTierText() string {
	if x != nil {
		return x.IconTierText
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Item) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *Item) GetIlvl() int32 {
	if x != nil {
		return x.Ilvl
	}
	return 0
}

func (x *Item) GetSocketedItems() []byte {
	if x != nil {
		return x.SocketedItems
	}
	return nil
}

func (x *Item) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Item) GetRequirements() []byte {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Item) GetEnchantMods() []byte {
	if x != nil {
		return x.EnchantMods
	}
	return nil
}

func (x *Item) GetRuneMods() []byte {
	if x != nil {
		return x.RuneMods
	}
	return nil
}

func (x *Item) GetImplicitMods() []byte {
	if x != nil {
		return x.ImplicitMods
	}
	return nil
}

func (x *Item) GetExplicitMods() []byte {
	if x != nil {
		return x.ExplicitMods
	}
	return nil
}

func (x *Item) GetFracturedMods() []byte {
	if x != nil {
		return x.FracturedMods
	}
	return nil
}

func (x *Item) GetDesecratedMods() []byte {
	if x != nil {
		return x.DesecratedMods
	}
	return nil
}

func (x *Item) GetFlavourText() string {
	if x != nil {
		return x.FlavourText
	}
	return ""
}

func (x *Item) GetDescrText() string {
	if x != nil {
		return x.DescrText
	}
	return ""
}

func (x *Item) GetSecDescrText() string {
	if x != nil {
		return x.SecDescrText
	}
	return ""
}

func (x *Item) GetSupport() bool {
	if x != nil {
		return x.Support
	}
	return false
}

func (x *Item) GetDuplicated() bool {
	if x != nil {
		return x.Duplicated
	}
	return false
}

func (x *Item) GetCorrupted() bool {
	if x != nil {
		return x.Corrupted
	}
	return false
}

func (x *Item) GetSanctified() bool {
	if x != nil {
		return x.Sanctified
	}
	return false
}

func (x *Item) GetDesecrated() bool {
	if x != nil {
		return x.Desecrated
	}
	return false
}

type InsertPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *Price                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPriceRequest) Reset() {
	*x = InsertPriceRequest{}
	mi := &file_rdpc_rdpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPriceRequest) ProtoMessage() {}

func (x *InsertPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPriceRequest.ProtoReflect.Descriptor instead.
func (*InsertPriceRequest) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{3}
}

func (x *InsertPriceRequest) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type InsertPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPriceResponse) Reset() {
	*x = InsertPriceResponse{}
	mi := &file_rdpc_rdpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPriceResponse) ProtoMessage() {}

func (x *InsertPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPriceResponse.ProtoReflect.Descriptor instead.
func (*InsertPriceResponse) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{4}
}

func (x *InsertPriceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	CurrencyId    string                 `protobuf:"bytes,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Volume        int32                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	League        string                 `protobuf:"bytes,6,opt,name=league,proto3" json:"league,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_rdpc_rdpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_rdpc_rdpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_rdpc_rdpc_proto_rawDescGZIP(), []int{5}
}

func (x *Price) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Price) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Price) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *Price) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Price) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Price) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

func (x *Price) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_rdpc_rdpc_proto protoreflect.FileDescriptor

const file_rdpc_rdpc_proto_rawDesc = "" +
	"\n" +
	"\x0frdpc/rdpc.proto\x12\x04rdpc\"-\n" +
	"\x0fCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\")\n" +
	"\x05Items\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".rdpc.ItemR\x05items\"\xe3\x06\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x04 \x01(\tR\vsubCategory\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12$\n" +
	"\x0eicon_tier_text\x18\x06 \x01(\tR\ficonTierText\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1b\n" +
	"\tbase_type\x18\b \x01(\tR\bbaseType\x12\x16\n" +
	"\x06rarity\x18\t \x01(\tR\x06rarity\x12\f\n" +
	"\x01w\x18\n" +
	" \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\v \x01(\x05R\x01h\x12\x12\n" +
	"\x04ilvl\x18\f \x01(\x05R\x04ilvl\x12%\n" +
	"\x0esocketed_items\x18\r \x01(\fR\rsocketedItems\x12\x1e\n" +
	"\n" +
	"properties\x18\x0e \x01(\fR\n" +
	"properties\x12\"\n" +
	"\frequirements\x18\x0f \x01(\fR\frequirements\x12!\n" +
	"\fenchant_mods\x18\x10 \x01(\fR\venchantMods\x12\x1b\n" +
	"\trune_mods\x18\x11 \x01(\fR\bruneMods\x12#\n" +
	"\rimplicit_mods\x18\x12 \x01(\fR\fimplicitMods\x12#\n" +
	"\rexplicit_mods\x18\x13 \x01(\fR\fexplicitMods\x12%\n" +
	"\x0efractured_mods\x18\x14 \x01(\fR\rfracturedMods\x12'\n" +
	"\x0fdesecrated_mods\x18\x15 \x01(\fR\x0edesecratedMods\x12!\n" +
	"\fflavour_text\x18\x16 \x01(\tR\vflavourText\x12\x1d\n" +
	"\n" +
	"descr_text\x18\x17 \x01(\tR\tdescrText\x12$\n" +
	"\x0esec_descr_text\x18\x18 \x01(\tR\fsecDescrText\x12\x18\n" +
	"\asupport\x18\x19 \x01(\bR\asupport\x12\x1e\n" +
	"\n" +
	"duplicated\x18\x1a \x01(\bR\n" +
	"duplicated\x12\x1c\n" +
	"\tcorrupted\x18\x1b \x01(\bR\tcorrupted\x12\x1e\n" +
	"\n" +
	"sanctified\x18\x1c \x01(\bR\n" +
	"sanctified\x12\x1e\n" +
	"\n" +
	"desecrated\x18\x1d \x01(\bR\n" +
	"desecrated\"7\n" +
	"\x12InsertPriceRequest\x12!\n" +
	"\x05price\x18\x01 \x01(\v2\v.rdpc.PriceR\x05price\"%\n" +
	"\x13InsertPriceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbb\x01\n" +
	"\x05Price\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\tR\n" +
	"currencyId\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x05R\x06volume\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x16\n" +
	"\x06league\x18\x06 \x01(\tR\x06league\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp2\x8c\x01\n" +
	"\bDatabase\x12:\n" +
	"\x12GetItemsByCategory\x12\x15.rdpc.CategoryRequest\x1a\v.rdpc.Items\"\x00\x12D\n" +
	"\vInsertPrice\x12\x18.rdpc.InsertPriceRequest\x1a\x19.rdpc.InsertPriceResponse\"\x00B\x1cZ\x1agithub.com/Vyary/rdpc/rdpcb\x06proto3"

var (
	file_rdpc_rdpc_proto_rawDescOnce sync.Once
	file_rdpc_rdpc_proto_rawDescData []byte
)

func file_rdpc_rdpc_proto_rawDescGZIP() []byte {
	file_rdpc_rdpc_proto_rawDescOnce.Do(func() {
		file_rdpc_rdpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rdpc_rdpc_proto_rawDesc), len(file_rdpc_rdpc_proto_rawDesc)))
	})
	return file_rdpc_rdpc_proto_rawDescData
}

var file_rdpc_rdpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rdpc_rdpc_proto_goTypes = []any{
	(*CategoryRequest)(nil),     // 0: rdpc.CategoryRequest
	(*Items)(nil),               // 1: rdpc.Items
	(*Item)(nil),                // 2: rdpc.Item
	(*InsertPriceRequest)(nil),  // 3: rdpc.InsertPriceRequest
	(*InsertPriceResponse)(nil), // 4: rdpc.InsertPriceResponse
	(*Price)(nil),               // 5: rdpc.Price
}
var file_rdpc_rdpc_proto_depIdxs = []int32{
	2, // 0: rdpc.Items.items:type_name -> rdpc.Item
	5, // 1: rdpc.InsertPriceRequest.price:type_name -> rdpc.Price
	0, // 2: rdpc.Database.GetItemsByCategory:input_type -> rdpc.CategoryRequest
	3, // 3: rdpc.Database.InsertPrice:input_type -> rdpc.InsertPriceRequest
	1, // 4: rdpc.Database.GetItemsByCategory:output_type -> rdpc.Items
	4, // 5: rdpc.Database.InsertPrice:output_type -> rdpc.InsertPriceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rdpc_rdpc_proto_init() }
func file_rdpc_rdpc_proto_init() {
	if File_rdpc_rdpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rdpc_rdpc_proto_rawDesc), len(file_rdpc_rdpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rdpc_rdpc_proto_goTypes,
		DependencyIndexes: file_rdpc_rdpc_proto_depIdxs,
		MessageInfos:      file_rdpc_rdpc_proto_msgTypes,
	}.Build()
	File_rdpc_rdpc_proto = out.File
	file_rdpc_rdpc_proto_goTypes = nil
	file_rdpc_rdpc_proto_depIdxs = nil
}
